"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ParamType = exports.LogBuiltInMetadata = exports.LogAction = exports.LogSource = exports.LogType = exports.DayOfWeek = exports.visitEndpointOnAnotherServer = exports.addDBEditorEndpoints = exports.initExpressKitCollections = exports.handleSuccess = exports.handleError = exports.genRouteHandler = exports.initServer = exports.shuffleArray = exports.capitalize = exports.someAsync = exports.mapAsync = exports.forEachAsync = exports.filterAsync = exports.everyAsync = exports.prefixWithAOrAn = exports.getLocalTimeInfo = exports.genCommaList = exports.compareArraysByProp = exports.extractProp = exports.genCSV = exports.getMonthName = exports.parallelLimit = exports.onlyKeepLetters = exports.stringsToHumanReadableList = exports.getPartOfDay = exports.getHumanReadableDate = exports.startMinWait = exports.getTimestampFromTimeInfoInET = exports.getTimeInfoInET = exports.getOrdinal = exports.waitMs = exports.sum = exports.roundToNumDecimals = exports.padZerosLeft = exports.padDecimalZeros = exports.forceNumIntoBounds = exports.floorToNumDecimals = exports.ceilToNumDecimals = exports.avg = exports.abbreviate = exports.DAY_IN_MS = exports.HOUR_IN_MS = exports.MINUTE_IN_MS = exports.ErrorWithCode = void 0;
// Import dce-commonkit
var dce_commonkit_1 = require("dce-commonkit");
Object.defineProperty(exports, "abbreviate", { enumerable: true, get: function () { return dce_commonkit_1.abbreviate; } });
Object.defineProperty(exports, "avg", { enumerable: true, get: function () { return dce_commonkit_1.avg; } });
Object.defineProperty(exports, "ceilToNumDecimals", { enumerable: true, get: function () { return dce_commonkit_1.ceilToNumDecimals; } });
Object.defineProperty(exports, "floorToNumDecimals", { enumerable: true, get: function () { return dce_commonkit_1.floorToNumDecimals; } });
Object.defineProperty(exports, "forceNumIntoBounds", { enumerable: true, get: function () { return dce_commonkit_1.forceNumIntoBounds; } });
Object.defineProperty(exports, "padDecimalZeros", { enumerable: true, get: function () { return dce_commonkit_1.padDecimalZeros; } });
Object.defineProperty(exports, "padZerosLeft", { enumerable: true, get: function () { return dce_commonkit_1.padZerosLeft; } });
Object.defineProperty(exports, "roundToNumDecimals", { enumerable: true, get: function () { return dce_commonkit_1.roundToNumDecimals; } });
Object.defineProperty(exports, "sum", { enumerable: true, get: function () { return dce_commonkit_1.sum; } });
Object.defineProperty(exports, "waitMs", { enumerable: true, get: function () { return dce_commonkit_1.waitMs; } });
Object.defineProperty(exports, "getOrdinal", { enumerable: true, get: function () { return dce_commonkit_1.getOrdinal; } });
Object.defineProperty(exports, "getTimeInfoInET", { enumerable: true, get: function () { return dce_commonkit_1.getTimeInfoInET; } });
Object.defineProperty(exports, "getTimestampFromTimeInfoInET", { enumerable: true, get: function () { return dce_commonkit_1.getTimestampFromTimeInfoInET; } });
Object.defineProperty(exports, "startMinWait", { enumerable: true, get: function () { return dce_commonkit_1.startMinWait; } });
Object.defineProperty(exports, "getHumanReadableDate", { enumerable: true, get: function () { return dce_commonkit_1.getHumanReadableDate; } });
Object.defineProperty(exports, "getPartOfDay", { enumerable: true, get: function () { return dce_commonkit_1.getPartOfDay; } });
Object.defineProperty(exports, "stringsToHumanReadableList", { enumerable: true, get: function () { return dce_commonkit_1.stringsToHumanReadableList; } });
Object.defineProperty(exports, "onlyKeepLetters", { enumerable: true, get: function () { return dce_commonkit_1.onlyKeepLetters; } });
Object.defineProperty(exports, "parallelLimit", { enumerable: true, get: function () { return dce_commonkit_1.parallelLimit; } });
Object.defineProperty(exports, "getMonthName", { enumerable: true, get: function () { return dce_commonkit_1.getMonthName; } });
Object.defineProperty(exports, "genCSV", { enumerable: true, get: function () { return dce_commonkit_1.genCSV; } });
Object.defineProperty(exports, "extractProp", { enumerable: true, get: function () { return dce_commonkit_1.extractProp; } });
Object.defineProperty(exports, "compareArraysByProp", { enumerable: true, get: function () { return dce_commonkit_1.compareArraysByProp; } });
Object.defineProperty(exports, "getLocalTimeInfo", { enumerable: true, get: function () { return dce_commonkit_1.getLocalTimeInfo; } });
Object.defineProperty(exports, "genCommaList", { enumerable: true, get: function () { return dce_commonkit_1.genCommaList; } });
Object.defineProperty(exports, "prefixWithAOrAn", { enumerable: true, get: function () { return dce_commonkit_1.prefixWithAOrAn; } });
Object.defineProperty(exports, "everyAsync", { enumerable: true, get: function () { return dce_commonkit_1.everyAsync; } });
Object.defineProperty(exports, "filterAsync", { enumerable: true, get: function () { return dce_commonkit_1.filterAsync; } });
Object.defineProperty(exports, "forEachAsync", { enumerable: true, get: function () { return dce_commonkit_1.forEachAsync; } });
Object.defineProperty(exports, "mapAsync", { enumerable: true, get: function () { return dce_commonkit_1.mapAsync; } });
Object.defineProperty(exports, "someAsync", { enumerable: true, get: function () { return dce_commonkit_1.someAsync; } });
Object.defineProperty(exports, "capitalize", { enumerable: true, get: function () { return dce_commonkit_1.capitalize; } });
Object.defineProperty(exports, "shuffleArray", { enumerable: true, get: function () { return dce_commonkit_1.shuffleArray; } });
Object.defineProperty(exports, "DayOfWeek", { enumerable: true, get: function () { return dce_commonkit_1.DayOfWeek; } });
Object.defineProperty(exports, "LogType", { enumerable: true, get: function () { return dce_commonkit_1.LogType; } });
Object.defineProperty(exports, "LogSource", { enumerable: true, get: function () { return dce_commonkit_1.LogSource; } });
Object.defineProperty(exports, "LogAction", { enumerable: true, get: function () { return dce_commonkit_1.LogAction; } });
Object.defineProperty(exports, "LogBuiltInMetadata", { enumerable: true, get: function () { return dce_commonkit_1.LogBuiltInMetadata; } });
Object.defineProperty(exports, "MINUTE_IN_MS", { enumerable: true, get: function () { return dce_commonkit_1.MINUTE_IN_MS; } });
Object.defineProperty(exports, "HOUR_IN_MS", { enumerable: true, get: function () { return dce_commonkit_1.HOUR_IN_MS; } });
Object.defineProperty(exports, "DAY_IN_MS", { enumerable: true, get: function () { return dce_commonkit_1.DAY_IN_MS; } });
Object.defineProperty(exports, "ErrorWithCode", { enumerable: true, get: function () { return dce_commonkit_1.ErrorWithCode; } });
Object.defineProperty(exports, "ParamType", { enumerable: true, get: function () { return dce_commonkit_1.ParamType; } });
// Import helpers
var initServer_1 = __importDefault(require("./helpers/initServer"));
exports.initServer = initServer_1.default;
var genRouteHandler_1 = __importDefault(require("./helpers/genRouteHandler"));
exports.genRouteHandler = genRouteHandler_1.default;
var handleError_1 = __importDefault(require("./helpers/handleError"));
exports.handleError = handleError_1.default;
var handleSuccess_1 = __importDefault(require("./helpers/handleSuccess"));
exports.handleSuccess = handleSuccess_1.default;
var addDBEditorEndpoints_1 = __importDefault(require("./helpers/addDBEditorEndpoints"));
exports.addDBEditorEndpoints = addDBEditorEndpoints_1.default;
var visitEndpointOnAnotherServer_1 = __importDefault(require("./helpers/visitEndpointOnAnotherServer"));
exports.visitEndpointOnAnotherServer = visitEndpointOnAnotherServer_1.default;
var initExpressKitCollections_1 = __importDefault(require("./helpers/initExpressKitCollections"));
exports.initExpressKitCollections = initExpressKitCollections_1.default;
//# sourceMappingURL=index.js.map